SaveTimer: 200
KillBeforeText: 'Number of kills: '
KillAfterText: '.'
TimeBeforeText: 'Time played: '
TimeAfterText: '.'
BlockPlaceBeforeText: 'Blocks placed: '
BlockPlaceAfterText: '.'
BlockBreakBeforeText: 'Blocks broken: '
BlockBreakAfterText: '.'
JoinBeforeText: 'Number of joins: '
JoinAfterText: '.'
PVPDeathBeforeText: 'Number of PVP deaths: '
PVPDeathAfterText: '.'
PlayerNotFound: 'That user was either incorrect or has not played here.'